#! /bin/bash

#dependencies: ipcalc, iproute2, dnsmasq, radvd

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit 1
fi

tmpfolder=$(cat /dev/urandom | base64 | head -c 8)
mkdir "/tmp/${tmpfolder}"

four_flag='true'
six_flag='true'
interface=''
network='192.168.138.0/24'
verbose='false'

print_usage() {
  printf "Usage: -i <interface> define the downstream interface"
}

while getopts '46i:r:v' flag; do
  case "${flag}" in
    4) six_flag='false' ;;
    6) four_flag='false' ;;
    i) interface="${OPTARG}" ;;
    r) ip4space="${OPTARG}" ;;
    v) verbose='true' ;;
    *) print_usage
       exit 1 ;;
  esac
done

# check if interface is an existing interface
if ! ip link show ${interface} >/dev/null; then
    printf "Interface does not exist!"
    exit 1
fi

touch /tmp/${tmpfolder}/dnsmasq.conf

if ${four_flag}; then
  # füge lokale ipv4 addressen hinzu
  echo "[#] ip addr add $(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMin:/{print $2}')/$(ipcalc ${network} -b | awk -F'= ' '/Netmask:/{print $2}') dev ${interface}"
  ip addr add $(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMin:/{print $2}')/$(ipcalc ${network} -b | awk -F'= ' '/Netmask:/{print $2}') dev ${interface}

  # configure dhcp
  echo "[*] Configuring DNSmasq as DHCP."
  echo -e "dhcp-range=$(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMin:/{print $2}'),$(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMax:/{print $2}'),24h\ndhcp-option=option:router,$(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMin:/{print $2}')\ndhcp-option=option:dns-server,$(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMin:/{print $2}')\ndhcp-option=option:netmask,$(ipcalc ${network} -b | awk -F"[ ',]+" '/Netmask:/{print $2}')" >> /tmp/${tmpfolder}/dnsmasq.conf
  echo -e "listen-address=$(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMin:/{print $2}')" >> /tmp/${tmpfolder}/dnsmasq.conf
fi

if ${six_flag}; then
  # füge lokale ipv6 addressen hinzu
  echo "[!] pass v6 config. not implemented yet"
  # starte radvd
fi

# start dns
echo "[*] Configuring DNSmasq as DNS"
echo -e "#! /bin/bash\n\necho [+] \$1 \$2 \$3 >> /tmp/${tmpfolder}/dhcp.log" > /tmp/${tmpfolder}/dhcp.sh
chmod +x /tmp/${tmpfolder}/dhcp.sh
touch /tmp/${tmpfolder}/dhcp.log
echo -e "port=53\nlog-facility=/var/log/dnsmasq.log\ndhcp-script=/tmp/${tmpfolder}/dhcp.sh" >> /tmp/${tmpfolder}/dnsmasq.conf
echo "[#] dnsmasq -C /tmp/${tmpfolder}/dnsmasq.conf"
dnsmasq -C /tmp/${tmpfolder}/dnsmasq.conf

tail -f /tmp/${tmpfolder}/dhcp.log &
read

# cleanup code
echo "[*] killing ad deleting address"
kill "$(cat /var/run/dnsmasq.pid)"
ip addr del $(ipcalc ${network} -b | awk -F"[ ',]+" '/HostMin:/{print $2}')/$(ipcalc ${network} -b | awk -F'= ' '/Netmask:/{print $2}') dev ${interface}
